In [117]:
def getjobdescriptionsaslist(df):
    """
    This Method puts all jobdescriptions of a df into one list of strings
    
    Parameters
    ----------
    df : dateframe 
        The Job dataframe from which to take the descriptions from
    
    Returns
    -------
    descrstr : list
        A List of strings filled with all job descriptions doc by doc
    """
    #get all descriptions
    descrstr = []
    for i in range(len(df)):
        newstr = removespecials(df.iloc[i,2].lower())
        descrstr += [newstr]
    return descrstr

In [165]:
def getjobdescriptions(df):
    """
    This Method puts all jobdescriptions of a df into one string
    
    Parameters
    ----------
    df : dataframe          
        The Job dataframe from which to take the descriptions from
    
    Returns
    -------
    string : descrstr
        Wich is filled with all job descriptions at once
    """
    #get all descriptions
    descrstr = ""
    for i in range(len(df)):
        descrstr =descrstr +" "+ df.iloc[i,2]
    return (removespecials(descrstr))

In [118]:
def removespecials(str):
    """
    This Method removes specialcaracters
    
    Parameters
    ----------
    str : string
        The string from whom those specialcharacters shall be removed
        
    Returns
    -------
    string
         without those specialcaracters
    """
    return str.replace("◾", "").replace("(", "").replace(")", "").replace("[", "").replace("]", "")

In [119]:
def cossim(vec, doc0, doc1):    
    """
    This Method compares vector similarity within a term-document-matrix using cosine simularitys
    
    Parameters
    ----------    
    vec : term-document-matrix
    
    doc0 : vector 
        Documentvector
    doc1 : vector 
        Documentvector
    
    Returns
    -------
    sim : {'0','1'} 
      a value between 0 and 1, whereas 0 means no similarity and 1 means equality
    """
    #Ähnlichkeiten zwischen 2 Dokumenten
    from sklearn.metrics.pairwise import cosine_similarity
    vec1 = np.array(vec[doc0].toarray())
    vec2 = np.array(vec[doc1].toarray())
    sim = (cosine_similarity(vec1, vec2))
    return sim


In [120]:
def ttm(vector):  
    """
    This Method builds a term-term matrix 

    Parameters
    ----------
    vector : matrix
    term-document-matrix

    Returns
    -------
    term-term-matrix
    """
    #similaritys between terms in a matrix
    from sklearn.metrics.pairwise import cosine_similarity
    vec = vector.toarray()
    vec = vec.transpose()
    
    #the Terms axis is 0
    dim0 = vec.shape[0]
    termtermmat = np.empty([dim0,dim0]) 

    for x in range(dim0):
        for y in range(dim0):
            termtermmat[x,y]= cosine_similarity([vec[x]],[vec[y]])

    return termtermmat


In [ ]:
def ttm(vector):
    """
    This Method builds a term-term matrix

    Parameters
    ----------
    vector : term-document-matrix

    Returns
    -------
    term-term-matrix
    """
    #similaritys between terms in a matrix
    from sklearn.metrics.pairwise import cosine_similarity
    vec = vector.toarray()
    vec = vec.transpose()
    
    #the Terms axis is 0
    dim0 = vec.shape[0]
    termtermmat = np.empty([dim0,dim0]) 

    for x in range(dim0):
        for y in range(dim0):
            termtermmat[x,y]= cosine_similarity([vec[x]],[vec[y]])

    return termtermmat

In [ ]:
def ttm(vector):
    """
    This Method builds a term-term matrix 

    Parameters
    ----------
    vector : term-document-matrix

    Returns
    -------
    term-term-matrix
    """
    #similaritys between terms in a matrix
    from sklearn.metrics.pairwise import cosine_similarity
    vec = vector.toarray()
    vec = vec.transpose()
    
    #the Terms axis is 0
    dim0 = vec.shape[0]
    termtermmat = np.empty([dim0,dim0]) 

    for x in range(dim0):
        for y in range(dim0):
            termtermmat[x,y]= cosine_similarity([vec[x]],[vec[y]])

    return termtermmat

In [123]:
def getterms(df):
    """
    This Method gets all terms out of a dataframe and returns them as a string list
    Parameters
    ----------
    df : dataframe
        The dataframe from which the terms shall be selected

    Returns
    -------
    terms : stringlist
        With all terms of that dataframe
    """
    terms = []
    for i in range(len(df)):
        terms += [df.iloc[i,1].lower()]
    return terms

In [124]:
def nowhitespace(textlist):
    """
    This Method eliminates all whitespaces out of a textlist

    Parameters
    ----------
    textlist : list
        List with strings with too many whitespaces

    Returns
    -------
    textlist : list 
        Stringlist without whitespaces within those string
    """
    for i in range(len(textlist)):
        textlist[i] = textlist[i].replace(" ", "")
    return textlist

In [125]:
def replacespace(docs, termsorg,terms):
    """
    This Method replaces terms with spaces with terms without spaces and vice versa
    (Needed, to count compound propernuns as one noun)

    Parameters
    ----------
    docs : list
        Document list /string list
    termsorg : stringlist 
        Terms in ther original form
    terms : Stringlist
        Terms in the form the originals shall be replaced

    Returns
    -------
    docs : list
        documentlist with switched up terms
    """
    for i in range(len(docs)):
        for t in range(len(terms)):
            docs[i] = docs[i].replace(termsorg[t].lower(), terms[t].lower())
            #print(i, termsorg[t].lower(),terms[t].lower() )
    return(docs)

In [134]:
import pandas as pd

nounsde = r"C:\Users\thegy\Documents\Studium\HS FL 4\Mining\DFs\nouns_de.csv"
nounsen = r"C:\Users\thegy\Documents\Studium\HS FL 4\Mining\DFs\nouns_en.csv"
jobdf = r"C:\Users\thegy\Documents\Studium\HS FL 4\Mining\DFs\jobdf.csv"

nounsde= pd.read_csv(nounsde, delimiter = ";", decimal=",")
nounsen = pd.read_csv(nounsen, delimiter = ";", decimal=",")
jobdf = pd.read_csv(jobdf, delimiter = ";", decimal=",")

In [146]:
"""
Get nterms of dataframe with proper nouns
Compile them into term-document-matrixes
Compare Docs similaritys with cosine simularity
Create Term-Term-Matrix with term simularitys
"""
import numpy as np
df = nounsde
nterms = 20


#ged rid of those whitespaces between compound nouns, because otherwise those compound nouns would have been counted as 2 single words
termsorg = getterms(df[:nterms])
terms = nowhitespace(termsorg.copy())

#print(termsorg)
#print(terms)

docs = getjobdescriptionsaslist(jobdf)

#get rid of whitespaces in those terms within the docs
docs = replacespace(docs, termsorg,terms)

In [147]:
#get Count-Vectorizer - Term-Document-Matrix
from sklearn.feature_extraction.text import CountVectorizer
cvectorizer = CountVectorizer()
cvectorizer.fit(terms)
cvocab = cvectorizer.vocabulary_
cvec = cvectorizer.transform(docs)

#get Tfidf-Vectorizer - Term-Document-Matrix
from sklearn.feature_extraction.text import TfidfVectorizer
tvectorizer = TfidfVectorizer()
tvectorizer.fit(terms)
tvocab = tvectorizer.vocabulary_
tvec = tvectorizer.transform(docs)

print(cvec.toarray())
print(cvec.shape)

[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(400, 20)


In [148]:
#compare docs
doc0 = 1
doc1 = 7
sim0 = cossim(cvec,doc0,doc1)
sim1 = cossim(tvec,doc0,doc1)
print(sim0,sim1)

[[0.]] [[0.]]


In [149]:
#compare terms in a term-term-matrix (own build)
tttm = ttm(tvec)

In [150]:
#Allocate columns to terms
name = tvectorizer.get_feature_names()
name = replacespace(name, terms, termsorg)

dfmat ={}
for i in range(len(name)):
    dfmat[name[i]]=tttm[i]

ttdf = pd.DataFrame(dfmat, index = name)
print(ttdf)

                       analytics  big data  business intelligence  bwl  \
analytics               1.000000  0.153324               0.227709  0.0   
big data                0.153324  1.000000               0.067555  0.0   
business intelligence   0.227709  0.067555               1.000000  0.0   
bwl                     0.000000  0.000000               0.000000  0.0   
data analytics          0.213415  0.047578               0.134810  0.0   
data engineering        0.119023  0.158272               0.078090  0.0   
data mining             0.104023  0.191655               0.026038  0.0   
data science            0.287374  0.120292               0.074423  0.0   
data warehouse          0.123998  0.109431               0.117368  0.0   
deep learning           0.076501  0.163434               0.007456  0.0   
java                    0.110687  0.318698               0.045360  0.0   
ki                      0.000000  0.000000               0.000000  0.0   
machine learning        0.239248  0.20

In [151]:
ttdf.to_csv(r"C:\Users\thegy\Documents\Studium\HS FL 4\Mining\DFs\ttm.csv", sep=";",decimal=",",index=False)