In [117]:
def getjobdescriptionsaslist(df):
    """
    This Method puts all jobdescriptions of a df into one list of strings
    @param df: The Job dataframe from which to take the descriptions from
    @return: list of strings filled with all job descriptions doc by doc
    """
    #get all descriptions
    descrstr = []
    for i in range(len(df)):
        newstr = removespecials(df.iloc[i,2].lower())
        descrstr += [newstr]
    return descrstr

In [165]:
def getjobdescriptions(df):
    """
    This Method puts all jobdescriptions of a df into one string
    @param df: The Job dataframe from which to take the descriptions from
    @return: string filled with all job descriptions at once
    """
    #get all descriptions
    descrstr = ""
    for i in range(len(df)):
        descrstr =descrstr +" "+ df.iloc[i,2]
    return (removespecials(descrstr))

In [118]:
def removespecials(str):
    """
    This Method removes specialcaracters
    @param str: the string from whom those specialcharacters shall be removed
    @return: string without those specialcaracters
    """
    return str.replace("◾", "").replace("(", "").replace(")", "").replace("[", "").replace("]", "")

In [119]:
"""
This Method compares vector similarity within a term-document-matrix using cosine simularitys
@param vec: term-document-matrix
@param doc0: Documentvector
@param doc1: Documentvector
@return: a value between 0 and 1, whereas 0 means no similarity and 1 means equality
"""
def cossim(vec, doc0, doc1):    
    #Ähnlichkeiten zwischen 2 Dokumenten
    from sklearn.metrics.pairwise import cosine_similarity
    vec1 = np.array(vec[doc0].toarray())
    vec2 = np.array(vec[doc1].toarray())
    sim = (cosine_similarity(vec1, vec2))
    return sim


In [120]:
"""
This Method builds a term-term matrix 
@param vector: term-document-matrix
@return: a term-term-matrix
"""
def ttm(vector):   
    #similaritys between terms in a matrix
    from sklearn.metrics.pairwise import cosine_similarity
    vec = vector.toarray()
    vec = vec.transpose()
    
    #the Terms axis is 0
    dim0 = vec.shape[0]
    termtermmat = np.empty([dim0,dim0]) 

    for x in range(dim0):
        for y in range(dim0):
            termtermmat[x,y]= cosine_similarity([vec[x]],[vec[y]])

    return termtermmat


In [ ]:
"""
This Method builds a term-term matrix 
@param vector: term-document-matrix
@return: a term-term-matrix
"""
def ttm(vector):   
    #similaritys between terms in a matrix
    from sklearn.metrics.pairwise import cosine_similarity
    vec = vector.toarray()
    vec = vec.transpose()
    
    #the Terms axis is 0
    dim0 = vec.shape[0]
    termtermmat = np.empty([dim0,dim0]) 

    for x in range(dim0):
        for y in range(dim0):
            termtermmat[x,y]= cosine_similarity([vec[x]],[vec[y]])

    return termtermmat

In [ ]:
"""
This Method builds a term-term matrix 
@param vector: term-document-matrix
@return: a term-term-matrix
"""
def ttm(vector):   
    #similaritys between terms in a matrix
    from sklearn.metrics.pairwise import cosine_similarity
    vec = vector.toarray()
    vec = vec.transpose()
    
    #the Terms axis is 0
    dim0 = vec.shape[0]
    termtermmat = np.empty([dim0,dim0]) 

    for x in range(dim0):
        for y in range(dim0):
            termtermmat[x,y]= cosine_similarity([vec[x]],[vec[y]])

    return termtermmat

In [123]:
"""
This Method gets all terms out of a dataframe and returns them as a string list
@param df: the dataframe from which the terms shall be selected
@return: stringlist with all terms of that dataframe
"""
def getterms(df):
    terms = []
    for i in range(len(df)):
        terms += [df.iloc[i,1].lower()]
    return terms

In [124]:
"""
This Method eliminates all whitespaces out of a textlist
@param textlist: tlist with strings with too many whitespaces
@return: stringlist without whitespaces within those string
"""
def nowhitespace(textlist):
    for i in range(len(textlist)):
        textlist[i] = textlist[i].replace(" ", "")
    return textlist

In [125]:
"""
This Method replaces terms with spaces with terms without spaces and vice versa
(Needed, to count compound propernuns as one noun)
@param docs: document list /string list)
@param termsorg: (stringlist) terms in ther original form
@param terms: (stringlist) terms in the form the originals shall be replaced
@return: documentlist with switched up terms
"""
def replacespace(docs, termsorg,terms):
    for i in range(len(docs)):
        for t in range(len(terms)):
            docs[i] = docs[i].replace(termsorg[t].lower(), terms[t].lower())
            #print(i, termsorg[t].lower(),terms[t].lower() )
    return(docs)

In [134]:
import pandas as pd

nounsde = r"C:\Users\thegy\Documents\Studium\HS FL 4\Mining\DFs\nouns_de.csv"
nounsen = r"C:\Users\thegy\Documents\Studium\HS FL 4\Mining\DFs\nouns_en.csv"
jobdf = r"C:\Users\thegy\Documents\Studium\HS FL 4\Mining\DFs\jobdf.csv"

nounsde= pd.read_csv(nounsde, delimiter = ";", decimal=",")
nounsen = pd.read_csv(nounsen, delimiter = ";", decimal=",")
jobdf = pd.read_csv(jobdf, delimiter = ";", decimal=",")

In [146]:
"""
Get nterms of dataframe with proper nouns
Compile them into term-document-matrixes
Compare Docs similaritys with cosine simularity
Create Term-Term-Matrix with term simularitys
"""
import numpy as np
df = nounsde
nterms = 20


#ged rid of those whitespaces between compound nouns, because otherwise those compound nouns would have been counted as 2 single words
termsorg = getterms(df[:nterms])
terms = nowhitespace(termsorg.copy())

#print(termsorg)
#print(terms)

docs = getjobdescriptionsaslist(jobdf)

#get rid of whitespaces in those terms within the docs
docs = replacespace(docs, termsorg,terms)

In [147]:
#get Count-Vectorizer - Term-Document-Matrix
from sklearn.feature_extraction.text import CountVectorizer
cvectorizer = CountVectorizer()
cvectorizer.fit(terms)
cvocab = cvectorizer.vocabulary_
cvec = cvectorizer.transform(docs)

#get Tfidf-Vectorizer - Term-Document-Matrix
from sklearn.feature_extraction.text import TfidfVectorizer
tvectorizer = TfidfVectorizer()
tvectorizer.fit(terms)
tvocab = tvectorizer.vocabulary_
tvec = tvectorizer.transform(docs)

print(cvec.toarray())
print(cvec.shape)

[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(400, 20)


In [148]:
#compare docs
doc0 = 1
doc1 = 7
sim0 = cossim(cvec,doc0,doc1)
sim1 = cossim(tvec,doc0,doc1)
print(sim0,sim1)

[[0.]] [[0.]]


In [149]:
#compare terms in a term-term-matrix (own build)
tttm = ttm(tvec)

In [150]:
#Allocate columns to terms
name = tvectorizer.get_feature_names()
name = replacespace(name, terms, termsorg)

dfmat ={}
for i in range(len(name)):
    dfmat[name[i]]=tttm[i]

ttdf = pd.DataFrame(dfmat, index = name)
print(ttdf)

                       analytics  big data  business intelligence  bwl  \
analytics               1.000000  0.153324               0.227709  0.0   
big data                0.153324  1.000000               0.067555  0.0   
business intelligence   0.227709  0.067555               1.000000  0.0   
bwl                     0.000000  0.000000               0.000000  0.0   
data analytics          0.213415  0.047578               0.134810  0.0   
data engineering        0.119023  0.158272               0.078090  0.0   
data mining             0.104023  0.191655               0.026038  0.0   
data science            0.287374  0.120292               0.074423  0.0   
data warehouse          0.123998  0.109431               0.117368  0.0   
deep learning           0.076501  0.163434               0.007456  0.0   
java                    0.110687  0.318698               0.045360  0.0   
ki                      0.000000  0.000000               0.000000  0.0   
machine learning        0.239248  0.20

In [151]:
ttdf.to_csv(r"C:\Users\thegy\Documents\Studium\HS FL 4\Mining\DFs\ttm.csv", sep=";",decimal=",",index=False)

In [167]:
import spacy 
import numpy as np

df = nounsde
nterms = 20

termsorg = getterms(df[:nterms])
terms = nowhitespace(termsorg.copy())

docs = getjobdescriptions(jobdf)

from spacy.lang.de import German
nlp = spacy.load("de_core_news_sm")
#from spacy.lang.en import English
#nlp = spacy.load("en_core_web_sm") 

nlp.max_length = 2000000
doc = nlp(docs)

In [168]:
vec_arr = np.empty((len(docs), nlp.vocab.vectors_length))
for i in range(len(docs)):
    txt = docs[i]
    doc = nlp(txt)
    vec_arr[i] = doc.vector

ValueError: could not broadcast input array from shape (96,) into shape (0,)

In [ ]:
print(len(docs))

In [ ]:
print(nlp.vocab.vectors_length)